services:
  server:
    build:
      context: .
    container_name: backend-transfeera
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000

  db:
    image: mysql:latest
    restart: always
    container_name: database-transfeera
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=qwert9876
    ports:
      - 3307:3306
   
volumes:
  db-data:

